In [1]:
import torch

In [2]:
import torchvision

In [3]:
torch.cuda.is_available()

True

## Torch Tensors

In [4]:
a=torch.tensor([2,3,4])  ## 1-D Tensor
print(a)

tensor([2, 3, 4])


In [5]:
b=torch.tensor([[2,3,4],[1,1,2],[2,5,6],[3,1,2]]) ## 2-D Tensor
print(b)

tensor([[2, 3, 4],
        [1, 1, 2],
        [2, 5, 6],
        [3, 1, 2]])


In [6]:
a.shape

torch.Size([3])

In [7]:
b.shape


torch.Size([4, 3])

In [8]:
a.size()

torch.Size([3])

In [9]:
b.size()

torch.Size([4, 3])

In [10]:
c=torch.FloatTensor([[2,3,4],[1,1,2],[2,5,6],[3,1,2]])
print(c)
print(c.dtype)
## or c=torch.tensor([[2,3,4],[1,1,2],[2,5,6],[3,1,2]], dtype = torch.float))

tensor([[2., 3., 4.],
        [1., 1., 2.],
        [2., 5., 6.],
        [3., 1., 2.]])
torch.float32


In [11]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(d)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)


In [12]:
print(c.mean())

tensor(2.6667)


In [13]:
print(c.std())

tensor(1.6143)


In [14]:
## The view function is meant to reshape the tensor.
#Note: If one of the dimensions is -1, its size can be inferred


print(b.view(-1,1))

tensor([[2],
        [3],
        [4],
        [1],
        [1],
        [2],
        [2],
        [5],
        [6],
        [3],
        [1],
        [2]])


In [15]:
print(b.view(12))

tensor([2, 3, 4, 1, 1, 2, 2, 5, 6, 3, 1, 2])


In [16]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.3000, 0.2158, 0.6379, 0.6333],
        [0.1464, 0.6686, 0.3828, 0.6516],
        [0.7061, 0.9562, 0.8775, 0.0073],
        [0.3791, 0.7744, 0.4179, 0.0290]])


In [17]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1 
r2 = torch.randn(4,4)
print(r2)

tensor([[ 0.7091,  0.6619,  0.7505,  1.8537],
        [-0.5208,  1.2305, -0.6398, -0.3411],
        [-0.6735,  0.9252, -0.8813,  0.7463],
        [-0.2351, -1.9208,  0.1469,  0.5081]])


In [18]:

#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([8, 7, 6, 9, 6])
torch.int64


In [19]:
# number of elements in in_array
print(torch.numel(in_array))

5


In [20]:
print(torch.numel(r2))

16


In [21]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [22]:
r2_like = torch.randn_like(r2, dtype=torch.double)    # Convert the data type of the tensor
print(r2_like)

tensor([[ 1.5099, -1.7668,  0.0044,  0.5706],
        [ 1.0411,  0.1127,  0.1209, -1.7096],
        [-0.3101, -0.8570, -0.5132,  1.3337],
        [ 0.4532, -0.1253, -0.5171, -0.8180]], dtype=torch.float64)


In [23]:
# torch addition  - should be same size and data type

torch.add(r,r2)

tensor([[ 1.0090,  0.8777,  1.3884,  2.4870],
        [-0.3743,  1.8991, -0.2570,  0.3105],
        [ 0.0327,  1.8814, -0.0038,  0.7536],
        [ 0.1440, -1.1464,  0.5648,  0.5371]])

In [24]:
#In-place addition (change the value of r2)
r2.add_(r)    
print(r2)

tensor([[ 1.0090,  0.8777,  1.3884,  2.4870],
        [-0.3743,  1.8991, -0.2570,  0.3105],
        [ 0.0327,  1.8814, -0.0038,  0.7536],
        [ 0.1440, -1.1464,  0.5648,  0.5371]])


In [25]:
r2

tensor([[ 1.0090,  0.8777,  1.3884,  2.4870],
        [-0.3743,  1.8991, -0.2570,  0.3105],
        [ 0.0327,  1.8814, -0.0038,  0.7536],
        [ 0.1440, -1.1464,  0.5648,  0.5371]])

In [26]:
print(r2[:,1])

tensor([ 0.8777,  1.8991,  1.8814, -1.1464])


In [27]:
print(r2[:,2])

tensor([ 1.3884, -0.2570, -0.0038,  0.5648])


In [28]:
print(r2[1:2])

tensor([[-0.3743,  1.8991, -0.2570,  0.3105]])


In [30]:
a=r2[2,3]
print(a)
print(a.item())

tensor(0.7536)
0.7536143064498901


## Numpy Bridge

In [31]:
import numpy as np

In [32]:
#Converting a Torch Tensor to a NumPy Array

a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [33]:
b= a.numpy()

In [34]:
print(b)

[1. 1. 1. 1. 1.]


In [36]:
## adding a value to tensor also updates in numpy

a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [37]:
#Converting NumPy Array to Torch Tensor

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [38]:
#Move the tensor to the GPU

r2 = r2.cuda()
print(r2)

tensor([[ 1.0090,  0.8777,  1.3884,  2.4870],
        [-0.3743,  1.8991, -0.2570,  0.3105],
        [ 0.0327,  1.8814, -0.0038,  0.7536],
        [ 0.1440, -1.1464,  0.5648,  0.5371]], device='cuda:0')


In [40]:
## a list to a tensor

a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


## Tensor Concatenation

In [44]:
a=torch.randn(2,5)
b=torch.randn(3,5)
print(a)
print(b)

tensor([[ 2.2638e+00, -1.1291e-01,  1.5809e-01, -8.2572e-02,  9.9030e-01],
        [-4.1175e-01, -5.5146e-01, -2.7331e-05, -1.4958e+00, -8.9868e-01]])
tensor([[ 0.3964, -0.4102,  0.3903,  0.6421, -0.0637],
        [ 0.8654, -1.6711, -1.4422, -0.7363, -1.0845],
        [-0.7836, -0.2264, -0.4642, -0.1211,  0.1501]])


In [45]:
concat_result=torch.cat([a,b])  ## to concatenate the rows. here column no should be same
print(concat_result)

tensor([[ 2.2638e+00, -1.1291e-01,  1.5809e-01, -8.2572e-02,  9.9030e-01],
        [-4.1175e-01, -5.5146e-01, -2.7331e-05, -1.4958e+00, -8.9868e-01],
        [ 3.9645e-01, -4.1020e-01,  3.9029e-01,  6.4211e-01, -6.3674e-02],
        [ 8.6536e-01, -1.6711e+00, -1.4422e+00, -7.3629e-01, -1.0845e+00],
        [-7.8356e-01, -2.2640e-01, -4.6416e-01, -1.2111e-01,  1.5014e-01]])


In [46]:
a1=torch.randn(4,5)
b1=torch.randn(4,6)
print(a1)
print(b1)

tensor([[-0.0385,  0.1070,  0.1886,  2.3155,  0.5453],
        [ 0.4490,  1.9607,  0.1351,  0.9469, -0.6826],
        [-0.6071,  3.3037, -0.2219, -0.5492,  1.3400],
        [ 0.7405,  0.0688, -1.0394,  0.4645, -0.8857]])
tensor([[ 0.8058, -0.4638,  1.3963, -0.8888, -0.1176,  0.4801],
        [ 0.4315, -0.9795, -0.8720,  0.8809,  0.0892,  0.6306],
        [-1.1247, -0.5054,  1.4442, -0.9584,  0.6360, -0.3338],
        [-2.1757, -0.7360,  1.1958, -0.3365,  0.7206, -1.5264]])


In [47]:
concat_result1=torch.cat([a1,b1],1)  ## to concatenate the cols. here row no should be same
print(concat_result1)

tensor([[-0.0385,  0.1070,  0.1886,  2.3155,  0.5453,  0.8058, -0.4638,  1.3963,
         -0.8888, -0.1176,  0.4801],
        [ 0.4490,  1.9607,  0.1351,  0.9469, -0.6826,  0.4315, -0.9795, -0.8720,
          0.8809,  0.0892,  0.6306],
        [-0.6071,  3.3037, -0.2219, -0.5492,  1.3400, -1.1247, -0.5054,  1.4442,
         -0.9584,  0.6360, -0.3338],
        [ 0.7405,  0.0688, -1.0394,  0.4645, -0.8857, -2.1757, -0.7360,  1.1958,
         -0.3365,  0.7206, -1.5264]])


## Adding Dimensions to Tensors

In [50]:
c = torch.tensor([1, 2, 3, 4])
print(c.shape)
d = torch.unsqueeze(c, 0)    #Adds a dimension of 1 along a specified index
print(d)
print(d.shape)

torch.Size([4])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


In [51]:
e=torch.unsqueeze(c, 1)    #Adds a dimension of 1 along a specified index
print(e)
print(e.shape)

tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


## AutoGrad

In [52]:
# If requires_grad=True, the Tensor object keeps track of how it was created.

x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)

# both x and y have their required_grad set to true, therefore we an compute gradients with respect to them

z = x + y
print(z)


tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [53]:
print(z.grad_fn)

In [54]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [55]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x

s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [56]:
# By default, Tensors have `requires_grad=False`

x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y

# So you can't backprop through z
print(z.grad_fn)

False False
None


In [58]:
#Another way to set the requires_grad = True is

x.requires_grad_()
y.requires_grad_()

# z contains enough information to compute gradients, as we saw above

z = x + y
print(z.grad_fn)

In [59]:
# If any input to an operation has ``requires_grad=True``, so will the output

print(z.requires_grad)  # Now z has the computation history that relates itself to x and y

True


In [60]:
 # z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten.
    
newz = z.detach()
print(newz.grad_fn)    
    

None


In [61]:
## another example

x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [62]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)

#Perform element-wise multiplaction 
mul = torch.mul(m1,m2)

#Another way to perform element-wise multiplaction 
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
